packages:
  - "."
  - "projects/expense-tracker-js"

overrides:
  postcss: 8.5.10
  sharp: 0.35.3

allowBuilds:
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - sharp
  - unrs-resolver
